name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: snok/install-poetry@v1         # ← drops the CLI on PATH
        with:
          version: "2.1.x"                   # pin, or omit for latest

      - name: Ensure lockfile is up-to-date
        run: poetry lock --check

      - name: Install deps
        run: poetry install --no-interaction --no-ansi --no-root

      - name: Lint + format
        run: |
          poetry run ruff check .
          poetry run black --check .

      - name: Tests
        run: poetry run pytest -q

      - name: Ensure lockfile is up-to-date
        run: poetry lock --check


