name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout
      - uses: actions/checkout@v4

      # 2 Python 3.12 (with Poetry cache)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      # 3 Poetry itself
      - name: Install Poetry
        run: pip install --upgrade poetry

      # 4 Project dependencies (incl. dev extras such as pre-commit)
      - name: Install deps
        run: |
          poetry install --no-interaction --no-root

      # 5 Run every pre-commit hook on the full tree
      - name: Lint / format via pre-commit
        run: |
          poetry run pre-commit run --all-files --show-diff-on-failure

      # 6 Unit tests
      - name: Tests
        run: poetry run pytest -q
